### PR TITLE
Remove plan object and all conditions relying on it

### LINKED ISSUE #185: Removal of pro plan
The status panel spec was updated:
- there are no different types of plans anymore

**Update to rendering**
- rendering must not depend on the current plan anymore

Changes:
- always show popular patterns / common methods
- make sure that that plan-gating is in use

**Update the status panel:**
- See the updated spec at https://kite.quip.com/rVcJA1bIqZny/Kite-Status-Spec#QcWACA99QXi

Changes: 
- the header (first row} isn't changing anymore. It's always the same logo on the left and link on the right
- the middle column in the header (optional plan details) was removed
- `Get free pro` link was removed
- email verifications was removed, this isn't displayed anymore in the status panel
- the  menu items changed: `Help`  changed its position, `Kite Engine settings` was added for most editors

### PR DESCRIPTION
**Pull request by abe33**
Closes #185

### CODE REVIEW

**Comment by jansorg** [comment]
- [ ] I'm still seeing "Kite Basic" next to the logo. Remove "Kite Basic"
- [ ] Move Help link to 3rd instead of 5th

Apologies if some of this wasn't clear in the issue!

**Comment by jansorg** [comment]
@abe33 
- [ ] Help is 2nd, but should be 3rd in the list of links. See https://kite.quip.com/rVcJA1bIqZny/Kite-Status-Spec#QcWACAO7aGZ for a mockup
- [ ] I'm not seeing `Package settings` here. I'm unsure if this was the case before. If the extension has a sort of settings ui then please add a menu item to open it. See the mockup linked above for details

**Comment by abe33** [comment]
As for the `Package Settings` we can't do anything because VSCode don't allow us to do that.

**Comment by jansorg** [comment]
@abe33 could we merge this?

**Pull request merged**
