### PR TITLE
Feature autocorrect

### PR DESCRIPTION
**Pull request by abe33**

### CODE REVIEW

**Comment by jansorg** [comment]
I'm using VSCode 1.21.

@abe33 I'm getting this in the console (running a debug instance of VSCode from the main instance of VSCode). This was shown after saving a file with simple content.
I've executed `npm install` in the plugin's git repository before running VSCode.

```
C:\Program Files\Microsoft VS Code\Code.exe --debugBrkPluginHost=18724 --debugId=7744b279-76bf-4ae5-a864-8969bd120bae --extensionDevelopmentPath=C:\Users\jansorg\source\vscode-plugin 
TypeDefinition null
(node:6208) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Error: Error 501: not implemented

	at module.exports.getAutocorrectData.promisifyRequest.then.promisifyReadResponse.then.data (C:\Users\jansorg\source\vscode-plugin\src\kite-editor.js:187:17)
	at <anonymous>
	at Immediate._tickCallback (internal/process/next_tick.js:109:7)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)
TypeError: Cannot read property 'requested_buffer_hash' of undefined
	at module.exports.onWillSave.Promise.all.getAutocorrectData.then.data (C:\Users\jansorg\source\vscode-plugin\src\kite-editor.js:56:17)
	at <anonymous>
	at Immediate._tickCallback (internal/process/next_tick.js:109:7)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by jansorg** [comment]
@abe33 This is looking great! :)
I'm still seeing the newline issue here. Let me know how I can help to debug this.
This is what is shown after I saved the file:
screenshot_20180417_094044

(@mwichary I think it's a bit difficult to see whether the switch next to "Enable Error Rescue" is on or off. )

**Comment by jansorg** [comment]
@mwichary Maybe a colored know or background when enabled?

**Comment by mwichary** [comment]
@jansorg I think the disappearing of the entire bottom section + the graying out of the “Any time code is fixed” below in the disabled state should help in communicating what’s going on, so I’m not personally too worried. But if you’d like to experiment with the colour or the shape of the toggle, or have other ideas, please explore this further and we can chat!

**Comment by jansorg** [comment]
@abe33 I've updated the vscode plugin to the latest commit and started it in the VSCode host app (Run->Debug).
I'm getting this error on save:
screenshot_20180423_181348

**Comment by abe33** [comment]
@jansorg That's now fixed, the issue that while wanting to debug that stuff, the log statement was falsely making the promise resolves instead of getting rejected, resulting in the second error.

**Pull request merged**
