### PR TITLE
Fix ui

### PR DESCRIPTION
**Pull request by abe33**
This PR addresses UI and UX issues described in the project's issues. It includes all changes made in the `fix-behaviour` branch.

### CODE REVIEW

**Comment by jansorg** [comment]
@abe33 , cc @abmirayo Thanks, this look great!
I have a few minor things I noticed. As I wasn't involved in the previous discussions about this, some things might have been discusses already.

# Search
- [ ] I can't see that the first element is an input box ("Search identifier.."). It looks like a gray heading to me.
screenshot_20171110_114116
- [ ] The hint about the input element looks large here
screenshot_20171110_114543
- [ ] Currently the history displays the technical ID, e.g. "python;matplotlib.pyplot.plot". Is it possible to show the name instead?
screenshot_20171110_114233
- [ ] The elements in the history show a regular mouse pointer on hover. It should display the cursor for links, I think.

# Completions
- [ ] The documentation box has some whitespace before the header "Kite docs"
screenshot_20171110_114945

# Command "Docs for cursor"
- [ ] Is it possible to disable/hide this command in the list if there's no documentation for the current offset? (e.g. if there's whitespace or an unknown token at the current offset)

**Comment by abe33** [comment]
@jansorg I took the liberty to use an ordered list instead, that way I can answer point by point.

1. That's how the design is (here's the design document for reference: https://kite.quip.com/KXnMA8YrAfFc/VS-Code-UI-Spec)
2. fixed now
3. fixed now
4. fixed now
5. the space is created by vscode to display the `detail` field and was previously filled with the type. It's either we use the `detail` field to display the type, or we use markdown like now, with an empty space for the detail
6. unfortunately no, VSCode doesn't allow custom visibility rule for commands, we can't even target a scope inside the editor (as with Atom).

**Comment by jansorg** [comment]
@abe33 Thanks!

1. The autofocus solution is great
2. This is looking good here
3. **I still see ids here (probably the old ones). Newer items are not added to the list, I think. (Is there a way to reset the list?)**
4. Fixed
5. **Is it possible to move "Kite docs" into the whitespace?**
6. Okay.

7. **New issue:** After clicking on "Axes" in the first screenshot source code is displayed.
screenshot_20171114_125013
source-display

**Comment by abe33** [comment]
@jansorg here's for the 5

**Comment by jansorg** [comment]
@abe33 Re no 5: This is looking fine, I think. Thanks!

**Comment by abe33** [comment]
@jansorg 
7 is fixed & for 3 I added a `Kite: Reset Search History` command that will clean that (it does not update the view in real time though)

**Comment by jansorg** [comment]
@abe33 
- no. 5 is looking good
- Reset search history is working
- Nothing is added to the search history. How do I do that?
- 7 is not yet fixed (tested with latest fix-ui branch) (After clicking on "Axes" in the first screenshot source code is displayed.)

**Comment by jansorg** [comment]
@abe33 Thanks, the server fix also resolved the issue with the internal links. All issues reported above are resolved now, as far as I can see. 
I noticed these two new issues:
1. Open the search panel, enter "mat" and wait until matplotlib is rendered. Now `mat` is added to the search history and not `matplotlib`. I think the latter should be added as `mat` is not a valid identifier
2. Open the search panel, enter `mat`, wait a bit and then press backspace several times until all of `mat` was removed. A rendering of a python function is shown here but I expected that the initial page withthe history was shown. Try different speeds while pressing backspace, it seems like a timing issue to me.

**Comment by abe33** [comment]
@jansorg 
1. the thing is, your search was `mat`, not `matplotlib`, what if the results you search is the third in the list, should I register each entry as you scroll in them and have lotsa garbage in the history or should I just consider what you actually put in the text input? This is why I originally suggested that `kited` should handle that. 
2. It's probably a timing issue, looking into reproducing it

**Comment by jansorg** [comment]
@abe33 
1. My thought was that the history should only display items which actually exist. When I click on `mat` then nothing happens in the search bar, it seems to accept existing ids only atm.
Is this a possible solution? :
    - The history should still show the search input as you suggested. A click on a search input should work as if the user entered that text, i.e. the search input is updated, the suggestions are filled and the rendering of the first item is done.

**Comment by abe33** [comment]
@jansorg that's why I intended to do, but I think I messed up by reusing the same logic than when clicking on search results, that's now fixed, history items has their own logic in that they're filling the input and then start a search with that term

**Comment by jansorg** [comment]
@abe33 Thanks, the history is working nicely now!
I think the timing issue is still open (2. from above).

**Pull request merged**
