### PR TITLE
Fix behaviour

### PR DESCRIPTION
**Pull request by abe33**
cc @jansorg @abmirayo 

This PR addresses all points in kiteco/kiteco#4970.

### CODE REVIEW

**Comment by jansorg** [comment]
@abe33 , cc @abmirayo 
Thanks, this is looking very good!

I noticed a few minor issues:
- the type in an instance rendering isn't linked, i.e. clicking on the blue label doesn't open the type. Sample code (rendering for `x123`):
```python
import matplotlib
x123 = json.JSONEncoder()
```
- In the list of links: "L:inks for X" -> "Links about X"
- Tests are failing atm

**Comment by abe33** [comment]
Re type's link.

Is it what you're talking about: 

weird-link-behaviour

The fact that not all the link seems to be interactive?

**Comment by jansorg** [comment]
@abe33 Hm, for reasons unknown to me, the links in the instance rendering of `x123` is working now.
Before, the link was there but hovering didn't change the mouse pointer and clicking didn't do a thing. So it was similair to your screencast above.
Do ou have an idea what the cause for this might be?

**Comment by jansorg** [comment]
Yes, this seems to be the same thing. Only the right edge of the link is clickable here, ~10% of the linked area.
Do you how what the reasons might be for this?

**Pull request merged**
