### PR TITLE
Feature tour

### PR DESCRIPTION
**Pull request by abe33**
Ref #17

### CODE REVIEW

**Comment by jlozano** [comment]
Looks great! feel free to merge this when you are ready!

**Comment by jlozano** [comment]
@abe33 @abmirayo screenshots attached, let me know what you think!
completions
docs
expandpanel
hover





[vscode-tour-screenshots.zip](https://github.com/kiteco/vscode-plugin/files/1043528/vscode-tour-screenshots.zip)

**Comment by jlozano** [comment]
@abe33 some minor changes to reflect the changes proposed for the atom tour:

- Make Kite logo at top smaller.
- Move kite Logo next to the header text and make the header text have smaller font.
- Move the `Kite is your Coding Copilot` text to be part of the scrollable region and have it at the bottom.

The goal is to make the scrollable area atleast 70% of the height of a reasonably sized window.

**Comment by abe33** [comment]
@jlozano I've made some screenshots myself that matches the size/scale of what we're using for Atom, I'll only miss one for contextual menus, my os is in french so VSCode is showing me french locale in the context menu.

**Comment by jlozano** [comment]
@abe33 which context menu are you referring to?

**Comment by jlozano** [comment]
@abe33 for showing the tour, can we implement the same strategy we use in atom? Only show the kite tour after the plugin is first installed and by default do not show the kite tour on startup.

**Comment by jlozano** [comment]
@abe33 the resizing of the scrolling region looks good! One minor thing, can we move the `To manage Kite's permissions, click here` and `For more help topics, go to help.kite.com` to be not part of the scrollable region? I know this will make the scrollable region slightly smaller but I think these are important to show to the user. Sorry I should have clarified this in the original comment.

**Comment by abmirayo** [comment]
@jlozano @abe33 I think the screenshots look great, @abe33 were you able to resize/crop them for VS Code? If not, what size do you need?

**Comment by abe33** [comment]
@abmirayo If it's good for you, it's good for me. I just reused the same dimension as in Atom with pretty much the same scale.

@jlozano About context menu, we have a section in the tour that shows the custom contextual menus we're providing in Atom, but in VSCode the structure is a bit different, actually there's no Kite sub-menu, we're supporting the definition API so that `go to definition` works (but since it's VSCode that creates theses menus mine are displayed in french), and we have two more entries at the bottom for settings and permissions, we might want to have a screenshot of the context menus in english rather than in french.

**Comment by jlozano** [comment]
@abe33 got it! screenshots:

New hover:
screen shot 2017-06-06 at 11 24 24 pm

Context menus
contextmenu

Let me know if you need anything else or new ones!

**Comment by jlozano** [comment]
@abe33 I am not seeing the new tour at all now, even after i delete the kite.vscode folder and relaunch the debug application, any ideas?

**Comment by abe33** [comment]
@jlozano I guess the settings is still falsy as we're turning it off after the first display, you can access your settings in VSCode using the `Open User Settings` command, otherwise their `settings.json` file is located in `~/Library/Application Support/Code/User/settings.json`.

**Comment by jlozano** [comment]
@abe33 looks good, one minor thing: The text of the features seems center aligned in the screenshot; it should be left aligned, like the titles.

**Pull request merged**
